#!/opt/mydan/perl/bin/perl -I/data/myn2n

=head1 SYNOPSIS

 $0 [--port num]

=cut
use strict;
use warnings;

use MYN2N;
use MYDan::Util::OptConf;

$| ++;

my $option = MYDan::Util::OptConf->load();
my %o = $option->set( port => 9999 )->get( qw( port=i ) )->dump();

$0 = 'myn2n';

my @server = ( "localhost:22" ); 

MYN2N->new( %o, server => \@server )->run();
