#!/bin/bash

export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

os=$(uname)
_exit () { echo $1; sleep 60; exit 1; }

if [ "x$os" = "x" ];then
     _exit "uname fail"
fi

echo "os: $os";

if [ "x$os" == "xLinux" ] ;then
    ulimit -n 655350 || _exit "ulimit -n fail";
    ulimit -u 102400 || _exit "ulimit -u fail";
    ulimit -s 10240  || _exit "ulimit -s fail";
fi

exec /data/myn2n/myn2n --server x.x.x.x:5555 --port 7775
